### ISSUE TITLE
Latest Lambda AMI changes

### ISSUE THREAD

**Issue by mcnamee** [mandatoryprogrammer/dig-lambda-layer#1]
https://aws.amazon.com/blogs/compute/upcoming-updates-to-the-aws-lambda-execution-environment/

Firstly thanks so much for this layer! It's been working well for some time now.

I've tested against the new Lambda execution environment (using the opt-in method from the above link) - and unfortunately just get an error:

```
dig: error while loading shared libraries: libidn.so.11: cannot open shared object file: No such file or directory
```

(Note that it works successfully with the old env).

Are you able to either:

- Provide some docs on how to build a new layer using the new execution environment (and/or)
- Build a new layer that works with the new execution environment

**Comment by mandatoryprogrammer** [comment]
Fixed by you in b6f5fe7
